spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/user?useUnicode=true&charaterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: tkddnjs0823

  jpa:
    hibernate.ddl.auto: update
    generate-ddl: true
    show-sql: true
    properties:
     hibernate.format_sql: true
     hibernate.jdbc.time_zone: Asia/Seoul
     hibernate:
       dialect: org.hibernate.dialect.MariaDB10Dialect

  thymeleaf:
    cache: false
    mode: HTML

  devtools:
    livereload:
      enabled: true
      port: 35729
    restart:
      enabled: true
      poll-interval: 1s

graphql:
  servlet:
    mapping: /graphql
    enabled: true
    corsEnabled: true
    exception-handlers-enabled: true
    websocket:
     enabled: false